name: Excavator
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  excavate:
    runs-on: windows-latest
    name: Excavator
    steps:
      - uses: actions/checkout@main
      - name: Excavator
        uses: shovel-org/GithubActions@main
        env:
          GITH_EMAIL: jan.krueger.dev@outlook.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
